# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.2.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGridLayout, QGroupBox,
    QMainWindow, QMenu, QMenuBar, QRadioButton,
    QSizePolicy, QStatusBar, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(920, 640)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(920, 640))
        MainWindow.setMaximumSize(QSize(920, 640))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(240, 240, 240, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(227, 227, 227, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(160, 160, 160, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush2)
        brush5 = QBrush(QColor(72, 89, 111, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush5)
        brush6 = QBrush(QColor(105, 105, 105, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        brush7 = QBrush(QColor(0, 120, 215, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        brush8 = QBrush(QColor(0, 0, 255, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Link, brush8)
        brush9 = QBrush(QColor(255, 0, 255, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        brush10 = QBrush(QColor(245, 245, 245, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush10)
        palette.setBrush(QPalette.Active, QPalette.NoRole, brush)
        brush11 = QBrush(QColor(255, 255, 220, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush12 = QBrush(QColor(0, 0, 0, 128))
        brush12.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush13 = QBrush(QColor(0, 0, 0, 255))
        brush13.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Inactive, QPalette.NoRole, brush13)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        brush14 = QBrush(QColor(120, 120, 120, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        brush15 = QBrush(QColor(247, 247, 247, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush16 = QBrush(QColor(0, 0, 0, 255))
        brush16.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Disabled, QPalette.NoRole, brush16)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        MainWindow.setPalette(palette)
        icon = QIcon()
        icon.addFile(u"../img/app_icon.png", QSize(), QIcon.Normal, QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.000000000000000)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon1 = QIcon()
        icon1.addFile(u"../img/icon-open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon2 = QIcon()
        icon2.addFile(u"../img/icon-save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionUltimate_Guitar = QAction(MainWindow)
        self.actionUltimate_Guitar.setObjectName(u"actionUltimate_Guitar")
        self.actionChordPro = QAction(MainWindow)
        self.actionChordPro.setObjectName(u"actionChordPro")
        self.actionLaTeX_leadsheets = QAction(MainWindow)
        self.actionLaTeX_leadsheets.setObjectName(u"actionLaTeX_leadsheets")
        self.actionLaTeX_songs = QAction(MainWindow)
        self.actionLaTeX_songs.setObjectName(u"actionLaTeX_songs")
        self.actionLaTeX_songs.setEnabled(False)
        self.actionHK = QAction(MainWindow)
        self.actionHK.setObjectName(u"actionHK")
        self.actionConvert = QAction(MainWindow)
        self.actionConvert.setObjectName(u"actionConvert")
        icon3 = QIcon()
        icon3.addFile(u"../img/icon-convert.png", QSize(), QIcon.Normal, QIcon.On)
        self.actionConvert.setIcon(icon3)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayoutWidget = QWidget(self.centralwidget)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(0, 0, 921, 611))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setContentsMargins(10, 10, 10, 0)
        self.groupbox_in_format = QGroupBox(self.gridLayoutWidget)
        self.groupbox_in_format.setObjectName(u"groupbox_in_format")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.groupbox_in_format.sizePolicy().hasHeightForWidth())
        self.groupbox_in_format.setSizePolicy(sizePolicy1)
        self.groupbox_in_format.setMinimumSize(QSize(0, 80))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette1.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette1.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Link, brush8)
        palette1.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush10)
        palette1.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush17 = QBrush(QColor(0, 0, 0, 255))
        brush17.setStyle(Qt.NoBrush)
        palette1.setBrush(QPalette.Inactive, QPalette.NoRole, brush17)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush18 = QBrush(QColor(0, 0, 0, 255))
        brush18.setStyle(Qt.NoBrush)
        palette1.setBrush(QPalette.Disabled, QPalette.NoRole, brush18)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.groupbox_in_format.setPalette(palette1)
        self.rb_in_chopro = QRadioButton(self.groupbox_in_format)
        self.rb_in_chopro.setObjectName(u"rb_in_chopro")
        self.rb_in_chopro.setGeometry(QRect(170, 30, 121, 17))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette2.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette2.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Link, brush8)
        palette2.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette2.setBrush(QPalette.Active, QPalette.AlternateBase, brush10)
        palette2.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette2.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette2.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush19 = QBrush(QColor(0, 0, 0, 255))
        brush19.setStyle(Qt.NoBrush)
        palette2.setBrush(QPalette.Inactive, QPalette.NoRole, brush19)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette2.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette2.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette2.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush20 = QBrush(QColor(0, 0, 0, 255))
        brush20.setStyle(Qt.NoBrush)
        palette2.setBrush(QPalette.Disabled, QPalette.NoRole, brush20)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.rb_in_chopro.setPalette(palette2)
        self.rb_in_hk = QRadioButton(self.groupbox_in_format)
        self.rb_in_hk.setObjectName(u"rb_in_hk")
        self.rb_in_hk.setGeometry(QRect(170, 52, 121, 17))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette3.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette3.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Link, brush8)
        palette3.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette3.setBrush(QPalette.Active, QPalette.AlternateBase, brush10)
        palette3.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette3.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette3.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush21 = QBrush(QColor(0, 0, 0, 255))
        brush21.setStyle(Qt.NoBrush)
        palette3.setBrush(QPalette.Inactive, QPalette.NoRole, brush21)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette3.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette3.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette3.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette3.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush22 = QBrush(QColor(0, 0, 0, 255))
        brush22.setStyle(Qt.NoBrush)
        palette3.setBrush(QPalette.Disabled, QPalette.NoRole, brush22)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.rb_in_hk.setPalette(palette3)
        self.rb_in_ug = QRadioButton(self.groupbox_in_format)
        self.rb_in_ug.setObjectName(u"rb_in_ug")
        self.rb_in_ug.setGeometry(QRect(20, 30, 109, 17))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette4.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
        palette4.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette4.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette4.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette4.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Link, brush8)
        palette4.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette4.setBrush(QPalette.Active, QPalette.AlternateBase, brush10)
        palette4.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette4.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette4.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush23 = QBrush(QColor(0, 0, 0, 255))
        brush23.setStyle(Qt.NoBrush)
        palette4.setBrush(QPalette.Inactive, QPalette.NoRole, brush23)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette4.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette4.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette4.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette4.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette4.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush24 = QBrush(QColor(0, 0, 0, 255))
        brush24.setStyle(Qt.NoBrush)
        palette4.setBrush(QPalette.Disabled, QPalette.NoRole, brush24)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.rb_in_ug.setPalette(palette4)
        self.rb_in_ug.setChecked(True)
        self.rb_in_latex_songs = QRadioButton(self.groupbox_in_format)
        self.rb_in_latex_songs.setObjectName(u"rb_in_latex_songs")
        self.rb_in_latex_songs.setEnabled(False)
        self.rb_in_latex_songs.setGeometry(QRect(20, 52, 109, 17))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette5.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette5.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush)
        palette5.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette5.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette5.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette5.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Link, brush8)
        palette5.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette5.setBrush(QPalette.Active, QPalette.AlternateBase, brush10)
        palette5.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette5.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette5.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette5.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette5.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush25 = QBrush(QColor(0, 0, 0, 255))
        brush25.setStyle(Qt.NoBrush)
        palette5.setBrush(QPalette.Inactive, QPalette.NoRole, brush25)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette5.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette5.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette5.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette5.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette5.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush26 = QBrush(QColor(0, 0, 0, 255))
        brush26.setStyle(Qt.NoBrush)
        palette5.setBrush(QPalette.Disabled, QPalette.NoRole, brush26)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.rb_in_latex_songs.setPalette(palette5)
        self.rb_in_latex_leadsheets = QRadioButton(self.groupbox_in_format)
        self.rb_in_latex_leadsheets.setObjectName(u"rb_in_latex_leadsheets")
        self.rb_in_latex_leadsheets.setGeometry(QRect(310, 30, 120, 20))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette6.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette6.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush)
        palette6.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette6.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette6.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette6.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Link, brush8)
        palette6.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette6.setBrush(QPalette.Active, QPalette.AlternateBase, brush10)
        palette6.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette6.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette6.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette6.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush27 = QBrush(QColor(0, 0, 0, 255))
        brush27.setStyle(Qt.NoBrush)
        palette6.setBrush(QPalette.Inactive, QPalette.NoRole, brush27)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette6.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette6.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette6.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette6.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette6.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush28 = QBrush(QColor(0, 0, 0, 255))
        brush28.setStyle(Qt.NoBrush)
        palette6.setBrush(QPalette.Disabled, QPalette.NoRole, brush28)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.rb_in_latex_leadsheets.setPalette(palette6)

        self.gridLayout.addWidget(self.groupbox_in_format, 0, 0, 1, 1)

        self.groupbox_out_format = QGroupBox(self.gridLayoutWidget)
        self.groupbox_out_format.setObjectName(u"groupbox_out_format")
        self.groupbox_out_format.setEnabled(True)
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette7.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette7.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush)
        palette7.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette7.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette7.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette7.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Link, brush8)
        palette7.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette7.setBrush(QPalette.Active, QPalette.AlternateBase, brush10)
        palette7.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette7.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette7.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette7.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette7.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush29 = QBrush(QColor(0, 0, 0, 255))
        brush29.setStyle(Qt.NoBrush)
        palette7.setBrush(QPalette.Inactive, QPalette.NoRole, brush29)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette7.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette7.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette7.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette7.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette7.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush30 = QBrush(QColor(0, 0, 0, 255))
        brush30.setStyle(Qt.NoBrush)
        palette7.setBrush(QPalette.Disabled, QPalette.NoRole, brush30)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.groupbox_out_format.setPalette(palette7)
        self.groupbox_out_format.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.groupbox_out_format.setFlat(False)
        self.rb_out_ug = QRadioButton(self.groupbox_out_format)
        self.rb_out_ug.setObjectName(u"rb_out_ug")
        self.rb_out_ug.setEnabled(False)
        self.rb_out_ug.setGeometry(QRect(20, 30, 131, 17))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette8.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette8.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette8.setBrush(QPalette.Active, QPalette.Text, brush)
        palette8.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette8.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette8.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette8.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette8.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Link, brush8)
        palette8.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette8.setBrush(QPalette.Active, QPalette.AlternateBase, brush10)
        palette8.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette8.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette8.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette8.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette8.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush31 = QBrush(QColor(0, 0, 0, 255))
        brush31.setStyle(Qt.NoBrush)
        palette8.setBrush(QPalette.Inactive, QPalette.NoRole, brush31)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette8.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette8.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette8.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette8.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette8.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette8.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush32 = QBrush(QColor(0, 0, 0, 255))
        brush32.setStyle(Qt.NoBrush)
        palette8.setBrush(QPalette.Disabled, QPalette.NoRole, brush32)
        palette8.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette8.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.rb_out_ug.setPalette(palette8)
        self.rb_out_ug.setChecked(False)
        self.rb_out_latex_songs = QRadioButton(self.groupbox_out_format)
        self.rb_out_latex_songs.setObjectName(u"rb_out_latex_songs")
        self.rb_out_latex_songs.setEnabled(False)
        self.rb_out_latex_songs.setGeometry(QRect(20, 52, 131, 17))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette9.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette9.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette9.setBrush(QPalette.Active, QPalette.Text, brush)
        palette9.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette9.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette9.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette9.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette9.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Link, brush8)
        palette9.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette9.setBrush(QPalette.Active, QPalette.AlternateBase, brush10)
        palette9.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette9.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette9.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette9.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette9.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette9.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette9.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette9.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette9.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush33 = QBrush(QColor(0, 0, 0, 255))
        brush33.setStyle(Qt.NoBrush)
        palette9.setBrush(QPalette.Inactive, QPalette.NoRole, brush33)
        palette9.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette9.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette9.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette9.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette9.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette9.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette9.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette9.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush34 = QBrush(QColor(0, 0, 0, 255))
        brush34.setStyle(Qt.NoBrush)
        palette9.setBrush(QPalette.Disabled, QPalette.NoRole, brush34)
        palette9.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette9.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.rb_out_latex_songs.setPalette(palette9)
        self.rb_out_chopro = QRadioButton(self.groupbox_out_format)
        self.rb_out_chopro.setObjectName(u"rb_out_chopro")
        self.rb_out_chopro.setEnabled(True)
        self.rb_out_chopro.setGeometry(QRect(170, 30, 121, 17))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette10.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette10.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette10.setBrush(QPalette.Active, QPalette.Text, brush)
        palette10.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette10.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette10.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette10.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Link, brush8)
        palette10.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette10.setBrush(QPalette.Active, QPalette.AlternateBase, brush10)
        palette10.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette10.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette10.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette10.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette10.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette10.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette10.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette10.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush35 = QBrush(QColor(0, 0, 0, 255))
        brush35.setStyle(Qt.NoBrush)
        palette10.setBrush(QPalette.Inactive, QPalette.NoRole, brush35)
        palette10.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette10.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette10.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette10.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette10.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette10.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette10.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette10.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush36 = QBrush(QColor(0, 0, 0, 255))
        brush36.setStyle(Qt.NoBrush)
        palette10.setBrush(QPalette.Disabled, QPalette.NoRole, brush36)
        palette10.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette10.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.rb_out_chopro.setPalette(palette10)
        self.rb_out_chopro.setChecked(True)
        self.rb_out_hk = QRadioButton(self.groupbox_out_format)
        self.rb_out_hk.setObjectName(u"rb_out_hk")
        self.rb_out_hk.setGeometry(QRect(170, 52, 121, 17))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette11.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette11.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette11.setBrush(QPalette.Active, QPalette.Text, brush)
        palette11.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette11.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette11.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette11.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette11.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette11.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Link, brush8)
        palette11.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette11.setBrush(QPalette.Active, QPalette.AlternateBase, brush10)
        palette11.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette11.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette11.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette11.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette11.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette11.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette11.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette11.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette11.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette11.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette11.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush37 = QBrush(QColor(0, 0, 0, 255))
        brush37.setStyle(Qt.NoBrush)
        palette11.setBrush(QPalette.Inactive, QPalette.NoRole, brush37)
        palette11.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette11.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette11.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette11.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette11.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette11.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette11.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette11.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette11.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette11.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette11.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush38 = QBrush(QColor(0, 0, 0, 255))
        brush38.setStyle(Qt.NoBrush)
        palette11.setBrush(QPalette.Disabled, QPalette.NoRole, brush38)
        palette11.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette11.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.rb_out_hk.setPalette(palette11)
        self.rb_out_latex_leadsheets = QRadioButton(self.groupbox_out_format)
        self.rb_out_latex_leadsheets.setObjectName(u"rb_out_latex_leadsheets")
        self.rb_out_latex_leadsheets.setGeometry(QRect(310, 30, 121, 17))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette12.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette12.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette12.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette12.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette12.setBrush(QPalette.Active, QPalette.Text, brush)
        palette12.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette12.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette12.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette12.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette12.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette12.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette12.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        palette12.setBrush(QPalette.Active, QPalette.Link, brush8)
        palette12.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette12.setBrush(QPalette.Active, QPalette.AlternateBase, brush10)
        palette12.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette12.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette12.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette12.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette12.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette12.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette12.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette12.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette12.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush39 = QBrush(QColor(0, 0, 0, 255))
        brush39.setStyle(Qt.NoBrush)
        palette12.setBrush(QPalette.Inactive, QPalette.NoRole, brush39)
        palette12.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette12.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette12.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette12.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette12.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette12.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette12.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette12.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette12.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette12.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette12.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette12.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush40 = QBrush(QColor(0, 0, 0, 255))
        brush40.setStyle(Qt.NoBrush)
        palette12.setBrush(QPalette.Disabled, QPalette.NoRole, brush40)
        palette12.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette12.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.rb_out_latex_leadsheets.setPalette(palette12)
        self.chb_chords_above = QCheckBox(self.groupbox_out_format)
        self.chb_chords_above.setObjectName(u"chb_chords_above")
        self.chb_chords_above.setGeometry(QRect(310, 52, 121, 17))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette13.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette13.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette13.setBrush(QPalette.Active, QPalette.Text, brush)
        palette13.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette13.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette13.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette13.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette13.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette13.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Link, brush8)
        palette13.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette13.setBrush(QPalette.Active, QPalette.AlternateBase, brush10)
        palette13.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette13.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette13.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette13.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette13.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette13.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette13.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush41 = QBrush(QColor(0, 0, 0, 255))
        brush41.setStyle(Qt.NoBrush)
        palette13.setBrush(QPalette.Inactive, QPalette.NoRole, brush41)
        palette13.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette13.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette13.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette13.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette13.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette13.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette13.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette13.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette13.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette13.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette13.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette13.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette13.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush42 = QBrush(QColor(0, 0, 0, 255))
        brush42.setStyle(Qt.NoBrush)
        palette13.setBrush(QPalette.Disabled, QPalette.NoRole, brush42)
        palette13.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette13.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.chb_chords_above.setPalette(palette13)

        self.gridLayout.addWidget(self.groupbox_out_format, 0, 1, 1, 1)

        self.text_out = QTextEdit(self.gridLayoutWidget)
        self.text_out.setObjectName(u"text_out")
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        brush43 = QBrush(QColor(127, 127, 127, 255))
        brush43.setStyle(Qt.SolidPattern)
        palette14.setBrush(QPalette.Active, QPalette.Dark, brush43)
        brush44 = QBrush(QColor(170, 170, 170, 255))
        brush44.setStyle(Qt.SolidPattern)
        palette14.setBrush(QPalette.Active, QPalette.Mid, brush44)
        palette14.setBrush(QPalette.Active, QPalette.Text, brush)
        palette14.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette14.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush45 = QBrush(QColor(255, 255, 192, 255))
        brush45.setStyle(Qt.SolidPattern)
        palette14.setBrush(QPalette.Active, QPalette.Base, brush45)
        palette14.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Shadow, brush)
        brush46 = QBrush(QColor(85, 170, 255, 255))
        brush46.setStyle(Qt.SolidPattern)
        palette14.setBrush(QPalette.Active, QPalette.Highlight, brush46)
        palette14.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Link, brush8)
        palette14.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette14.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        palette14.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette14.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette14.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette14.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette14.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette14.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette14.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette14.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette14.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush47 = QBrush(QColor(0, 0, 0, 255))
        brush47.setStyle(Qt.NoBrush)
        palette14.setBrush(QPalette.Inactive, QPalette.NoRole, brush47)
        palette14.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette14.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush43)
        palette14.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Dark, brush43)
        palette14.setBrush(QPalette.Disabled, QPalette.Mid, brush44)
        palette14.setBrush(QPalette.Disabled, QPalette.Text, brush43)
        palette14.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.ButtonText, brush43)
        palette14.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette14.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette14.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette14.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush48 = QBrush(QColor(0, 0, 0, 255))
        brush48.setStyle(Qt.NoBrush)
        palette14.setBrush(QPalette.Disabled, QPalette.NoRole, brush48)
        palette14.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette14.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.text_out.setPalette(palette14)
        font = QFont()
        font.setFamilies([u"Roboto Mono"])
        self.text_out.setFont(font)
        self.text_out.setLineWrapMode(QTextEdit.NoWrap)
        self.text_out.setReadOnly(True)

        self.gridLayout.addWidget(self.text_out, 1, 1, 1, 1)

        self.text_in = QTextEdit(self.gridLayoutWidget)
        self.text_in.setObjectName(u"text_in")
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Dark, brush43)
        palette15.setBrush(QPalette.Active, QPalette.Mid, brush44)
        palette15.setBrush(QPalette.Active, QPalette.Text, brush)
        palette15.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette15.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette15.setBrush(QPalette.Active, QPalette.Base, brush45)
        palette15.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette15.setBrush(QPalette.Active, QPalette.Highlight, brush46)
        palette15.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Link, brush8)
        palette15.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette15.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        palette15.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette15.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette15.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette15.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette15.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette15.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette15.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette15.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette15.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette15.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette15.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette15.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush49 = QBrush(QColor(0, 0, 0, 255))
        brush49.setStyle(Qt.NoBrush)
        palette15.setBrush(QPalette.Inactive, QPalette.NoRole, brush49)
        palette15.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette15.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette15.setBrush(QPalette.Disabled, QPalette.WindowText, brush43)
        palette15.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Dark, brush43)
        palette15.setBrush(QPalette.Disabled, QPalette.Mid, brush44)
        palette15.setBrush(QPalette.Disabled, QPalette.Text, brush43)
        palette15.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.ButtonText, brush43)
        palette15.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette15.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette15.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette15.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush50 = QBrush(QColor(0, 0, 0, 255))
        brush50.setStyle(Qt.NoBrush)
        palette15.setBrush(QPalette.Disabled, QPalette.NoRole, brush50)
        palette15.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette15.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.text_in.setPalette(palette15)
        self.text_in.setFont(font)
        self.text_in.setLineWrapMode(QTextEdit.NoWrap)

        self.gridLayout.addWidget(self.text_in, 1, 0, 1, 1)

        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 920, 22))
        palette16 = QPalette()
        self.menubar.setPalette(palette16)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuExamples = QMenu(self.menuFile)
        self.menuExamples.setObjectName(u"menuExamples")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuConvert = QMenu(self.menubar)
        self.menuConvert.setObjectName(u"menuConvert")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette17.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette17.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette17.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette17.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette17.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette17.setBrush(QPalette.Active, QPalette.Text, brush)
        palette17.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette17.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette17.setBrush(QPalette.Active, QPalette.Base, brush2)
        brush51 = QBrush(QColor(81, 93, 111, 255))
        brush51.setStyle(Qt.SolidPattern)
        palette17.setBrush(QPalette.Active, QPalette.Window, brush51)
        palette17.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette17.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette17.setBrush(QPalette.Active, QPalette.HighlightedText, brush2)
        palette17.setBrush(QPalette.Active, QPalette.Link, brush8)
        palette17.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette17.setBrush(QPalette.Active, QPalette.AlternateBase, brush10)
        palette17.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette17.setBrush(QPalette.Active, QPalette.ToolTipBase, brush11)
        palette17.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette17.setBrush(QPalette.Active, QPalette.PlaceholderText, brush12)
#endif
        palette17.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette17.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette17.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette17.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette17.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette17.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette17.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette17.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette17.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette17.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush10)
        brush52 = QBrush(QColor(0, 0, 0, 255))
        brush52.setStyle(Qt.NoBrush)
        palette17.setBrush(QPalette.Inactive, QPalette.NoRole, brush52)
        palette17.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush11)
        palette17.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette17.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette17.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette17.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette17.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette17.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette17.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette17.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette17.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette17.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette17.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette17.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette17.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette17.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette17.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        brush53 = QBrush(QColor(0, 0, 0, 255))
        brush53.setStyle(Qt.NoBrush)
        palette17.setBrush(QPalette.Disabled, QPalette.NoRole, brush53)
        palette17.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush11)
        palette17.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette17.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.statusbar.setPalette(palette17)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setSizeGripEnabled(True)
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConvert.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuExamples.menuAction())
        self.menuExamples.addAction(self.actionUltimate_Guitar)
        self.menuExamples.addAction(self.actionChordPro)
        self.menuExamples.addAction(self.actionLaTeX_leadsheets)
        self.menuExamples.addAction(self.actionLaTeX_songs)
        self.menuExamples.addAction(self.actionHK)
        self.menuHelp.addAction(self.actionAbout)
        self.menuConvert.addAction(self.actionConvert)

        self.retranslateUi(MainWindow)
        self.actionHK.triggered.connect(self.rb_in_hk.animateClick)
        self.actionChordPro.triggered.connect(self.rb_in_chopro.animateClick)
        self.actionUltimate_Guitar.triggered.connect(self.rb_in_ug.animateClick)
        self.actionLaTeX_songs.triggered.connect(self.rb_in_latex_leadsheets.animateClick)
        self.actionLaTeX_leadsheets.triggered.connect(self.rb_out_latex_leadsheets.animateClick)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Songs formats converter v0.1", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open...", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionUltimate_Guitar.setText(QCoreApplication.translate("MainWindow", u"Ultimate Guitar", None))
        self.actionChordPro.setText(QCoreApplication.translate("MainWindow", u"ChordPro", None))
        self.actionLaTeX_leadsheets.setText(QCoreApplication.translate("MainWindow", u"LaTeX (leadsheets)", None))
        self.actionLaTeX_songs.setText(QCoreApplication.translate("MainWindow", u"LaTeX (songs)", None))
        self.actionHK.setText(QCoreApplication.translate("MainWindow", u"HK", None))
        self.actionConvert.setText(QCoreApplication.translate("MainWindow", u"Convert", None))
#if QT_CONFIG(shortcut)
        self.actionConvert.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.groupbox_in_format.setTitle(QCoreApplication.translate("MainWindow", u"Input format", None))
        self.rb_in_chopro.setText(QCoreApplication.translate("MainWindow", u"ChordPro", None))
        self.rb_in_hk.setText(QCoreApplication.translate("MainWindow", u"HK(proprietary)", None))
        self.rb_in_ug.setText(QCoreApplication.translate("MainWindow", u"Ultimate Guitars", None))
        self.rb_in_latex_songs.setText(QCoreApplication.translate("MainWindow", u"LaTeX (songs)", None))
        self.rb_in_latex_leadsheets.setText(QCoreApplication.translate("MainWindow", u"LaTeX (leadsheets)", None))
        self.groupbox_out_format.setTitle(QCoreApplication.translate("MainWindow", u"Output Format", None))
        self.rb_out_ug.setText(QCoreApplication.translate("MainWindow", u"Ultimate Guitars", None))
        self.rb_out_latex_songs.setText(QCoreApplication.translate("MainWindow", u"LaTeX (songs)", None))
        self.rb_out_chopro.setText(QCoreApplication.translate("MainWindow", u"ChordPro", None))
        self.rb_out_hk.setText(QCoreApplication.translate("MainWindow", u"HK(proprietary)", None))
        self.rb_out_latex_leadsheets.setText(QCoreApplication.translate("MainWindow", u"LaTeX (leadsheets)", None))
        self.chb_chords_above.setText(QCoreApplication.translate("MainWindow", u"Chords above ?", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuExamples.setTitle(QCoreApplication.translate("MainWindow", u"Examples", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuConvert.setTitle(QCoreApplication.translate("MainWindow", u"Convert", None))
    # retranslateUi

